// Code generated by mockery. DO NOT EDIT.

package mockdomain

import (
	domain "budget-app/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, a
func (_m *MockAccountRepository) Create(ctx context.Context, a *domain.Account) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Account) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - a *domain.Account
func (_e *MockAccountRepository_Expecter) Create(ctx interface{}, a interface{}) *MockAccountRepository_Create_Call {
	return &MockAccountRepository_Create_Call{Call: _e.mock.On("Create", ctx, a)}
}

func (_c *MockAccountRepository_Create_Call) Run(run func(ctx context.Context, a *domain.Account)) *MockAccountRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Account))
	})
	return _c
}

func (_c *MockAccountRepository_Create_Call) Return(_a0 error) *MockAccountRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Account) error) *MockAccountRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAccountRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAccountRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockAccountRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAccountRepository_Delete_Call {
	return &MockAccountRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAccountRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockAccountRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAccountRepository_Delete_Call) Return(_a0 error) *MockAccountRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockAccountRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockAccountRepository) GetAll(ctx context.Context) ([]domain.Account, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Account, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Account); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockAccountRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAccountRepository_Expecter) GetAll(ctx interface{}) *MockAccountRepository_GetAll_Call {
	return &MockAccountRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockAccountRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockAccountRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAccountRepository_GetAll_Call) Return(_a0 []domain.Account, _a1 error) *MockAccountRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]domain.Account, error)) *MockAccountRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, a
func (_m *MockAccountRepository) Update(ctx context.Context, a *domain.Account) error {
	ret := _m.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Account) error); ok {
		r0 = rf(ctx, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAccountRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - a *domain.Account
func (_e *MockAccountRepository_Expecter) Update(ctx interface{}, a interface{}) *MockAccountRepository_Update_Call {
	return &MockAccountRepository_Update_Call{Call: _e.mock.On("Update", ctx, a)}
}

func (_c *MockAccountRepository_Update_Call) Run(run func(ctx context.Context, a *domain.Account)) *MockAccountRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Account))
	})
	return _c
}

func (_c *MockAccountRepository_Update_Call) Return(_a0 error) *MockAccountRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Account) error) *MockAccountRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBalance provides a mock function with given fields: ctx, accountID, delta
func (_m *MockAccountRepository) UpdateBalance(ctx context.Context, accountID int, delta float64) error {
	ret := _m.Called(ctx, accountID, delta)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBalance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, float64) error); ok {
		r0 = rf(ctx, accountID, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRepository_UpdateBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBalance'
type MockAccountRepository_UpdateBalance_Call struct {
	*mock.Call
}

// UpdateBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - accountID int
//   - delta float64
func (_e *MockAccountRepository_Expecter) UpdateBalance(ctx interface{}, accountID interface{}, delta interface{}) *MockAccountRepository_UpdateBalance_Call {
	return &MockAccountRepository_UpdateBalance_Call{Call: _e.mock.On("UpdateBalance", ctx, accountID, delta)}
}

func (_c *MockAccountRepository_UpdateBalance_Call) Run(run func(ctx context.Context, accountID int, delta float64)) *MockAccountRepository_UpdateBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(float64))
	})
	return _c
}

func (_c *MockAccountRepository_UpdateBalance_Call) Return(_a0 error) *MockAccountRepository_UpdateBalance_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRepository_UpdateBalance_Call) RunAndReturn(run func(context.Context, int, float64) error) *MockAccountRepository_UpdateBalance_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
