// Code generated by mockery. DO NOT EDIT.

package mockdomain

import (
	domain "budget-app/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDebtPaymentRepository is an autogenerated mock type for the DebtPaymentRepository type
type MockDebtPaymentRepository struct {
	mock.Mock
}

type MockDebtPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDebtPaymentRepository) EXPECT() *MockDebtPaymentRepository_Expecter {
	return &MockDebtPaymentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockDebtPaymentRepository) Create(ctx context.Context, p *domain.DebtPayment) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.DebtPayment) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDebtPaymentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDebtPaymentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.DebtPayment
func (_e *MockDebtPaymentRepository_Expecter) Create(ctx interface{}, p interface{}) *MockDebtPaymentRepository_Create_Call {
	return &MockDebtPaymentRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockDebtPaymentRepository_Create_Call) Run(run func(ctx context.Context, p *domain.DebtPayment)) *MockDebtPaymentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.DebtPayment))
	})
	return _c
}

func (_c *MockDebtPaymentRepository_Create_Call) Return(_a0 error) *MockDebtPaymentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDebtPaymentRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.DebtPayment) error) *MockDebtPaymentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockDebtPaymentRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDebtPaymentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDebtPaymentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockDebtPaymentRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockDebtPaymentRepository_Delete_Call {
	return &MockDebtPaymentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDebtPaymentRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockDebtPaymentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockDebtPaymentRepository_Delete_Call) Return(_a0 error) *MockDebtPaymentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDebtPaymentRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockDebtPaymentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByDebtID provides a mock function with given fields: ctx, debtID
func (_m *MockDebtPaymentRepository) GetByDebtID(ctx context.Context, debtID int) ([]domain.DebtPayment, error) {
	ret := _m.Called(ctx, debtID)

	if len(ret) == 0 {
		panic("no return value specified for GetByDebtID")
	}

	var r0 []domain.DebtPayment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]domain.DebtPayment, error)); ok {
		return rf(ctx, debtID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []domain.DebtPayment); ok {
		r0 = rf(ctx, debtID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DebtPayment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, debtID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDebtPaymentRepository_GetByDebtID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByDebtID'
type MockDebtPaymentRepository_GetByDebtID_Call struct {
	*mock.Call
}

// GetByDebtID is a helper method to define mock.On call
//   - ctx context.Context
//   - debtID int
func (_e *MockDebtPaymentRepository_Expecter) GetByDebtID(ctx interface{}, debtID interface{}) *MockDebtPaymentRepository_GetByDebtID_Call {
	return &MockDebtPaymentRepository_GetByDebtID_Call{Call: _e.mock.On("GetByDebtID", ctx, debtID)}
}

func (_c *MockDebtPaymentRepository_GetByDebtID_Call) Run(run func(ctx context.Context, debtID int)) *MockDebtPaymentRepository_GetByDebtID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockDebtPaymentRepository_GetByDebtID_Call) Return(_a0 []domain.DebtPayment, _a1 error) *MockDebtPaymentRepository_GetByDebtID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDebtPaymentRepository_GetByDebtID_Call) RunAndReturn(run func(context.Context, int) ([]domain.DebtPayment, error)) *MockDebtPaymentRepository_GetByDebtID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockDebtPaymentRepository) GetByID(ctx context.Context, id int) (*domain.DebtPayment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.DebtPayment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.DebtPayment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.DebtPayment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DebtPayment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDebtPaymentRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDebtPaymentRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockDebtPaymentRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockDebtPaymentRepository_GetByID_Call {
	return &MockDebtPaymentRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockDebtPaymentRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockDebtPaymentRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockDebtPaymentRepository_GetByID_Call) Return(_a0 *domain.DebtPayment, _a1 error) *MockDebtPaymentRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDebtPaymentRepository_GetByID_Call) RunAndReturn(run func(context.Context, int) (*domain.DebtPayment, error)) *MockDebtPaymentRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDebtPaymentRepository creates a new instance of MockDebtPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDebtPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDebtPaymentRepository {
	mock := &MockDebtPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
