// Code generated by mockery. DO NOT EDIT.

package mockdomain

import (
	domain "budget-app/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDebtRepository is an autogenerated mock type for the DebtRepository type
type MockDebtRepository struct {
	mock.Mock
}

type MockDebtRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDebtRepository) EXPECT() *MockDebtRepository_Expecter {
	return &MockDebtRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, d
func (_m *MockDebtRepository) Create(ctx context.Context, d *domain.Debt) error {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Debt) error); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDebtRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDebtRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - d *domain.Debt
func (_e *MockDebtRepository_Expecter) Create(ctx interface{}, d interface{}) *MockDebtRepository_Create_Call {
	return &MockDebtRepository_Create_Call{Call: _e.mock.On("Create", ctx, d)}
}

func (_c *MockDebtRepository_Create_Call) Run(run func(ctx context.Context, d *domain.Debt)) *MockDebtRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Debt))
	})
	return _c
}

func (_c *MockDebtRepository_Create_Call) Return(_a0 error) *MockDebtRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDebtRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Debt) error) *MockDebtRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockDebtRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDebtRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDebtRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockDebtRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockDebtRepository_Delete_Call {
	return &MockDebtRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDebtRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockDebtRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockDebtRepository_Delete_Call) Return(_a0 error) *MockDebtRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDebtRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockDebtRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockDebtRepository) GetAll(ctx context.Context) ([]domain.Debt, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Debt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Debt, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Debt); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Debt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDebtRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockDebtRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDebtRepository_Expecter) GetAll(ctx interface{}) *MockDebtRepository_GetAll_Call {
	return &MockDebtRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockDebtRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockDebtRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDebtRepository_GetAll_Call) Return(_a0 []domain.Debt, _a1 error) *MockDebtRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDebtRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]domain.Debt, error)) *MockDebtRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockDebtRepository) GetByID(ctx context.Context, id int) (*domain.Debt, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Debt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Debt, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Debt); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Debt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDebtRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDebtRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockDebtRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockDebtRepository_GetByID_Call {
	return &MockDebtRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockDebtRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockDebtRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockDebtRepository_GetByID_Call) Return(_a0 *domain.Debt, _a1 error) *MockDebtRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDebtRepository_GetByID_Call) RunAndReturn(run func(context.Context, int) (*domain.Debt, error)) *MockDebtRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, d
func (_m *MockDebtRepository) Update(ctx context.Context, d *domain.Debt) error {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Debt) error); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDebtRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDebtRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - d *domain.Debt
func (_e *MockDebtRepository_Expecter) Update(ctx interface{}, d interface{}) *MockDebtRepository_Update_Call {
	return &MockDebtRepository_Update_Call{Call: _e.mock.On("Update", ctx, d)}
}

func (_c *MockDebtRepository_Update_Call) Run(run func(ctx context.Context, d *domain.Debt)) *MockDebtRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Debt))
	})
	return _c
}

func (_c *MockDebtRepository_Update_Call) Return(_a0 error) *MockDebtRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDebtRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Debt) error) *MockDebtRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDebtRepository creates a new instance of MockDebtRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDebtRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDebtRepository {
	mock := &MockDebtRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
