// Code generated by mockery. DO NOT EDIT.

package mockdomain

import (
	domain "budget-app/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPurchaseRepository is an autogenerated mock type for the PurchaseRepository type
type MockPurchaseRepository struct {
	mock.Mock
}

type MockPurchaseRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPurchaseRepository) EXPECT() *MockPurchaseRepository_Expecter {
	return &MockPurchaseRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, p
func (_m *MockPurchaseRepository) Create(ctx context.Context, p *domain.PlannedPurchase) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PlannedPurchase) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPurchaseRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPurchaseRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.PlannedPurchase
func (_e *MockPurchaseRepository_Expecter) Create(ctx interface{}, p interface{}) *MockPurchaseRepository_Create_Call {
	return &MockPurchaseRepository_Create_Call{Call: _e.mock.On("Create", ctx, p)}
}

func (_c *MockPurchaseRepository_Create_Call) Run(run func(ctx context.Context, p *domain.PlannedPurchase)) *MockPurchaseRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.PlannedPurchase))
	})
	return _c
}

func (_c *MockPurchaseRepository_Create_Call) Return(_a0 error) *MockPurchaseRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPurchaseRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.PlannedPurchase) error) *MockPurchaseRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockPurchaseRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPurchaseRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPurchaseRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockPurchaseRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockPurchaseRepository_Delete_Call {
	return &MockPurchaseRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPurchaseRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockPurchaseRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockPurchaseRepository_Delete_Call) Return(_a0 error) *MockPurchaseRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPurchaseRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockPurchaseRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockPurchaseRepository) GetAll(ctx context.Context) ([]domain.PlannedPurchase, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.PlannedPurchase
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.PlannedPurchase, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.PlannedPurchase); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PlannedPurchase)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPurchaseRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockPurchaseRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPurchaseRepository_Expecter) GetAll(ctx interface{}) *MockPurchaseRepository_GetAll_Call {
	return &MockPurchaseRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockPurchaseRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockPurchaseRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockPurchaseRepository_GetAll_Call) Return(_a0 []domain.PlannedPurchase, _a1 error) *MockPurchaseRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPurchaseRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]domain.PlannedPurchase, error)) *MockPurchaseRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, p
func (_m *MockPurchaseRepository) Update(ctx context.Context, p *domain.PlannedPurchase) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.PlannedPurchase) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPurchaseRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPurchaseRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p *domain.PlannedPurchase
func (_e *MockPurchaseRepository_Expecter) Update(ctx interface{}, p interface{}) *MockPurchaseRepository_Update_Call {
	return &MockPurchaseRepository_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *MockPurchaseRepository_Update_Call) Run(run func(ctx context.Context, p *domain.PlannedPurchase)) *MockPurchaseRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.PlannedPurchase))
	})
	return _c
}

func (_c *MockPurchaseRepository_Update_Call) Return(_a0 error) *MockPurchaseRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPurchaseRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.PlannedPurchase) error) *MockPurchaseRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPurchaseRepository creates a new instance of MockPurchaseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPurchaseRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPurchaseRepository {
	mock := &MockPurchaseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
