// Code generated by mockery. DO NOT EDIT.

package mockdomain

import (
	domain "budget-app/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockInvestmentRepository is an autogenerated mock type for the InvestmentRepository type
type MockInvestmentRepository struct {
	mock.Mock
}

type MockInvestmentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInvestmentRepository) EXPECT() *MockInvestmentRepository_Expecter {
	return &MockInvestmentRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, inv
func (_m *MockInvestmentRepository) Create(ctx context.Context, inv *domain.Investment) error {
	ret := _m.Called(ctx, inv)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Investment) error); ok {
		r0 = rf(ctx, inv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInvestmentRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockInvestmentRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - inv *domain.Investment
func (_e *MockInvestmentRepository_Expecter) Create(ctx interface{}, inv interface{}) *MockInvestmentRepository_Create_Call {
	return &MockInvestmentRepository_Create_Call{Call: _e.mock.On("Create", ctx, inv)}
}

func (_c *MockInvestmentRepository_Create_Call) Run(run func(ctx context.Context, inv *domain.Investment)) *MockInvestmentRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Investment))
	})
	return _c
}

func (_c *MockInvestmentRepository_Create_Call) Return(_a0 error) *MockInvestmentRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInvestmentRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Investment) error) *MockInvestmentRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockInvestmentRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInvestmentRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockInvestmentRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockInvestmentRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockInvestmentRepository_Delete_Call {
	return &MockInvestmentRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockInvestmentRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockInvestmentRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockInvestmentRepository_Delete_Call) Return(_a0 error) *MockInvestmentRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInvestmentRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockInvestmentRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockInvestmentRepository) GetAll(ctx context.Context) ([]domain.Investment, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Investment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Investment, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Investment); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Investment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInvestmentRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockInvestmentRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockInvestmentRepository_Expecter) GetAll(ctx interface{}) *MockInvestmentRepository_GetAll_Call {
	return &MockInvestmentRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockInvestmentRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockInvestmentRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockInvestmentRepository_GetAll_Call) Return(_a0 []domain.Investment, _a1 error) *MockInvestmentRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInvestmentRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]domain.Investment, error)) *MockInvestmentRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, inv
func (_m *MockInvestmentRepository) Update(ctx context.Context, inv *domain.Investment) error {
	ret := _m.Called(ctx, inv)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Investment) error); ok {
		r0 = rf(ctx, inv)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInvestmentRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockInvestmentRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - inv *domain.Investment
func (_e *MockInvestmentRepository_Expecter) Update(ctx interface{}, inv interface{}) *MockInvestmentRepository_Update_Call {
	return &MockInvestmentRepository_Update_Call{Call: _e.mock.On("Update", ctx, inv)}
}

func (_c *MockInvestmentRepository_Update_Call) Run(run func(ctx context.Context, inv *domain.Investment)) *MockInvestmentRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Investment))
	})
	return _c
}

func (_c *MockInvestmentRepository_Update_Call) Return(_a0 error) *MockInvestmentRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInvestmentRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Investment) error) *MockInvestmentRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInvestmentRepository creates a new instance of MockInvestmentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvestmentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvestmentRepository {
	mock := &MockInvestmentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
