// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockdomain

import (
	domain "budget-app/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockBudgetRepository is an autogenerated mock type for the BudgetRepository type
type MockBudgetRepository struct {
	mock.Mock
}

type MockBudgetRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBudgetRepository) EXPECT() *MockBudgetRepository_Expecter {
	return &MockBudgetRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, b
func (_m *MockBudgetRepository) Create(ctx context.Context, b *domain.Budget) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Budget) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBudgetRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBudgetRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - b *domain.Budget
func (_e *MockBudgetRepository_Expecter) Create(ctx interface{}, b interface{}) *MockBudgetRepository_Create_Call {
	return &MockBudgetRepository_Create_Call{Call: _e.mock.On("Create", ctx, b)}
}

func (_c *MockBudgetRepository_Create_Call) Run(run func(ctx context.Context, b *domain.Budget)) *MockBudgetRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Budget))
	})
	return _c
}

func (_c *MockBudgetRepository_Create_Call) Return(_a0 error) *MockBudgetRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBudgetRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Budget) error) *MockBudgetRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockBudgetRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBudgetRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBudgetRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockBudgetRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockBudgetRepository_Delete_Call {
	return &MockBudgetRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBudgetRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockBudgetRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockBudgetRepository_Delete_Call) Return(_a0 error) *MockBudgetRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBudgetRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockBudgetRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *MockBudgetRepository) GetAll(ctx context.Context) ([]domain.Budget, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Budget
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Budget, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Budget); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Budget)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBudgetRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockBudgetRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBudgetRepository_Expecter) GetAll(ctx interface{}) *MockBudgetRepository_GetAll_Call {
	return &MockBudgetRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockBudgetRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockBudgetRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBudgetRepository_GetAll_Call) Return(_a0 []domain.Budget, _a1 error) *MockBudgetRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBudgetRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]domain.Budget, error)) *MockBudgetRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, b
func (_m *MockBudgetRepository) Update(ctx context.Context, b *domain.Budget) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Budget) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBudgetRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBudgetRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - b *domain.Budget
func (_e *MockBudgetRepository_Expecter) Update(ctx interface{}, b interface{}) *MockBudgetRepository_Update_Call {
	return &MockBudgetRepository_Update_Call{Call: _e.mock.On("Update", ctx, b)}
}

func (_c *MockBudgetRepository_Update_Call) Run(run func(ctx context.Context, b *domain.Budget)) *MockBudgetRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Budget))
	})
	return _c
}

func (_c *MockBudgetRepository_Update_Call) Return(_a0 error) *MockBudgetRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBudgetRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Budget) error) *MockBudgetRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBudgetRepository creates a new instance of MockBudgetRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBudgetRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBudgetRepository {
	mock := &MockBudgetRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
