// Code generated by mockery. DO NOT EDIT.

package mockdomain

import (
	domain "budget-app/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, t
func (_m *MockTransactionRepository) Create(ctx context.Context, t *domain.Transaction) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTransactionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - t *domain.Transaction
func (_e *MockTransactionRepository_Expecter) Create(ctx interface{}, t interface{}) *MockTransactionRepository_Create_Call {
	return &MockTransactionRepository_Create_Call{Call: _e.mock.On("Create", ctx, t)}
}

func (_c *MockTransactionRepository_Create_Call) Run(run func(ctx context.Context, t *domain.Transaction)) *MockTransactionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_Create_Call) Return(_a0 error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Transaction) error) *MockTransactionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockTransactionRepository) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTransactionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTransactionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTransactionRepository_Delete_Call {
	return &MockTransactionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTransactionRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *MockTransactionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionRepository_Delete_Call) Return(_a0 error) *MockTransactionRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_Delete_Call) RunAndReturn(run func(context.Context, int) error) *MockTransactionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, date, description, amount
func (_m *MockTransactionRepository) Exists(ctx context.Context, date string, description string, amount float64) (bool, error) {
	ret := _m.Called(ctx, date, description, amount)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64) (bool, error)); ok {
		return rf(ctx, date, description, amount)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64) bool); ok {
		r0 = rf(ctx, date, description, amount)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, float64) error); ok {
		r1 = rf(ctx, date, description, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockTransactionRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - date string
//   - description string
//   - amount float64
func (_e *MockTransactionRepository_Expecter) Exists(ctx interface{}, date interface{}, description interface{}, amount interface{}) *MockTransactionRepository_Exists_Call {
	return &MockTransactionRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, date, description, amount)}
}

func (_c *MockTransactionRepository_Exists_Call) Run(run func(ctx context.Context, date string, description string, amount float64)) *MockTransactionRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(float64))
	})
	return _c
}

func (_c *MockTransactionRepository_Exists_Call) Return(_a0 bool, _a1 error) *MockTransactionRepository_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_Exists_Call) RunAndReturn(run func(context.Context, string, string, float64) (bool, error)) *MockTransactionRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx, f
func (_m *MockTransactionRepository) GetAll(ctx context.Context, f domain.TransactionFilter) ([]domain.Transaction, error) {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.TransactionFilter) ([]domain.Transaction, error)); ok {
		return rf(ctx, f)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.TransactionFilter) []domain.Transaction); ok {
		r0 = rf(ctx, f)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.TransactionFilter) error); ok {
		r1 = rf(ctx, f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTransactionRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - f domain.TransactionFilter
func (_e *MockTransactionRepository_Expecter) GetAll(ctx interface{}, f interface{}) *MockTransactionRepository_GetAll_Call {
	return &MockTransactionRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, f)}
}

func (_c *MockTransactionRepository_GetAll_Call) Run(run func(ctx context.Context, f domain.TransactionFilter)) *MockTransactionRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.TransactionFilter))
	})
	return _c
}

func (_c *MockTransactionRepository_GetAll_Call) Return(_a0 []domain.Transaction, _a1 error) *MockTransactionRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_GetAll_Call) RunAndReturn(run func(context.Context, domain.TransactionFilter) ([]domain.Transaction, error)) *MockTransactionRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockTransactionRepository) GetByID(ctx context.Context, id int) (*domain.Transaction, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*domain.Transaction, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *domain.Transaction); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTransactionRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *MockTransactionRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTransactionRepository_GetByID_Call {
	return &MockTransactionRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTransactionRepository_GetByID_Call) Run(run func(ctx context.Context, id int)) *MockTransactionRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockTransactionRepository_GetByID_Call) Return(_a0 *domain.Transaction, _a1 error) *MockTransactionRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_GetByID_Call) RunAndReturn(run func(context.Context, int) (*domain.Transaction, error)) *MockTransactionRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// MonthlySums provides a mock function with given fields: ctx, month
func (_m *MockTransactionRepository) MonthlySums(ctx context.Context, month string) (float64, float64, error) {
	ret := _m.Called(ctx, month)

	if len(ret) == 0 {
		panic("no return value specified for MonthlySums")
	}

	var r0 float64
	var r1 float64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, float64, error)); ok {
		return rf(ctx, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, month)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) float64); ok {
		r1 = rf(ctx, month)
	} else {
		r1 = ret.Get(1).(float64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, month)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTransactionRepository_MonthlySums_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MonthlySums'
type MockTransactionRepository_MonthlySums_Call struct {
	*mock.Call
}

// MonthlySums is a helper method to define mock.On call
//   - ctx context.Context
//   - month string
func (_e *MockTransactionRepository_Expecter) MonthlySums(ctx interface{}, month interface{}) *MockTransactionRepository_MonthlySums_Call {
	return &MockTransactionRepository_MonthlySums_Call{Call: _e.mock.On("MonthlySums", ctx, month)}
}

func (_c *MockTransactionRepository_MonthlySums_Call) Run(run func(ctx context.Context, month string)) *MockTransactionRepository_MonthlySums_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransactionRepository_MonthlySums_Call) Return(income float64, expenses float64, err error) *MockTransactionRepository_MonthlySums_Call {
	_c.Call.Return(income, expenses, err)
	return _c
}

func (_c *MockTransactionRepository_MonthlySums_Call) RunAndReturn(run func(context.Context, string) (float64, float64, error)) *MockTransactionRepository_MonthlySums_Call {
	_c.Call.Return(run)
	return _c
}

// SpentByCategory provides a mock function with given fields: ctx, category, month
func (_m *MockTransactionRepository) SpentByCategory(ctx context.Context, category string, month string) (float64, error) {
	ret := _m.Called(ctx, category, month)

	if len(ret) == 0 {
		panic("no return value specified for SpentByCategory")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (float64, error)); ok {
		return rf(ctx, category, month)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) float64); ok {
		r0 = rf(ctx, category, month)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, category, month)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransactionRepository_SpentByCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SpentByCategory'
type MockTransactionRepository_SpentByCategory_Call struct {
	*mock.Call
}

// SpentByCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - category string
//   - month string
func (_e *MockTransactionRepository_Expecter) SpentByCategory(ctx interface{}, category interface{}, month interface{}) *MockTransactionRepository_SpentByCategory_Call {
	return &MockTransactionRepository_SpentByCategory_Call{Call: _e.mock.On("SpentByCategory", ctx, category, month)}
}

func (_c *MockTransactionRepository_SpentByCategory_Call) Run(run func(ctx context.Context, category string, month string)) *MockTransactionRepository_SpentByCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTransactionRepository_SpentByCategory_Call) Return(_a0 float64, _a1 error) *MockTransactionRepository_SpentByCategory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransactionRepository_SpentByCategory_Call) RunAndReturn(run func(context.Context, string, string) (float64, error)) *MockTransactionRepository_SpentByCategory_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, t
func (_m *MockTransactionRepository) Update(ctx context.Context, t *domain.Transaction) error {
	ret := _m.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) error); ok {
		r0 = rf(ctx, t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTransactionRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - t *domain.Transaction
func (_e *MockTransactionRepository_Expecter) Update(ctx interface{}, t interface{}) *MockTransactionRepository_Update_Call {
	return &MockTransactionRepository_Update_Call{Call: _e.mock.On("Update", ctx, t)}
}

func (_c *MockTransactionRepository_Update_Call) Run(run func(ctx context.Context, t *domain.Transaction)) *MockTransactionRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_Update_Call) Return(_a0 error) *MockTransactionRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Transaction) error) *MockTransactionRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
